# Introduction to NumPy and Pandas

In this file we are going to look at using numpy and pandas to deal with data

## NumPy

In [15]:
# %pip install numpy
# %pip install pandas

import pandas as pd
import numpy as np

In [19]:
list = [1, 2, 3, 5, 6, 7]

array = np.array(list)

print(array)

[1 2 3 5 6 7]

In [23]:
array = array * 2

print(array)

[ 4  8 12 20 24 28]

In [24]:
print(array)

[ 4  8 12 20 24 28]

In [28]:
print(array.sum(), array.mean(), array.min(), array.max())

96 16.0 4 28

In [29]:
below_target = array[array < 15]

print(below_target)

[ 4  8 12]

In [30]:
array.shape

(6,)

In [32]:
array.shape[0]

6

## 2D arrays

In [38]:
# 2D matrix
sales_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(sales_matrix, "\n" * 2, sales_matrix.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 (4, 3)

In [42]:
# Full sum
sales_matrix.sum()

78

In [41]:
# Column wise
sales_matrix.sum(axis=0)

array([22, 26, 30])

In [40]:
# Row wise
sales_matrix.sum(axis=1)

array([ 6, 15, 24, 33])

## 3D arrays

In [44]:
# 2 tables with 2 rows and 3 columns per table

array1 = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
])

In [45]:
array1

array([[[10, 20, 30],
        [40, 50, 60]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [46]:
array1.shape

(2, 2, 3)

One dimensional array with 12 elements (12,)

Two dimensional array with size (3, 4)

Three dimensional array with array size (2, 5, 4)

In [54]:
one_dim_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
two_dim_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
                 
three_dim_array = np.array([
    [
        [1, 2, 3, 4],
        [6, 7, 8, 9],
        [10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20 ,21]
    ],
    [
        [1, 2, 3, 4],
        [6, 7, 8, 9],
        [10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20 ,21]
    ]
])

In [55]:
print(one_dim_array.shape, two_dim_array.shape, three_dim_array.shape)

(12,) (3, 4) (2, 5, 4)

## Pandas

In [79]:
data = [['Adrian',20],['Bethany',23],['Chloe',41], ["David"]]
new_dict = {'Name':['Tom','Jane','Steve','Lucy'],'Sales':[250,300,350,400]}
dict_list = [{'Name':'Tom','Sales':250},{'Name':'Jane','Sales':300},{'Name':'Steve','Sales':350},{'Name':'Lucy','Sales':400}]

In [80]:
df_list = pd.DataFrame(data, columns=["Name", "Age"])
df_dict = pd.DataFrame(new_dict)
df_dict_list = pd.DataFrame(dict_list)

In [81]:
df_list

      Name   Age
0   Adrian  20.0
1  Bethany  23.0
2    Chloe  41.0
3    David   NaN

In [82]:
df_dict

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [83]:
df_dict_list

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [84]:
df_dict_list.loc[[1, 2]]

    Name  Sales
1   Jane    300
2  Steve    350

In [85]:
df_dict_list.loc[1]

Name     Jane
Sales     300
Name: 1, dtype: object

In [90]:
# Data cleaning
df_fill = pd.DataFrame(data, columns=["Name", "Age"])

df_fill.fillna("Dead")

         0     1
0   Adrian  20.0
1  Bethany  23.0
2    Chloe  41.0
3    David  Dead

In [87]:
# Data cleaning 
df_drop =pd.DataFrame(data, columns=["Name", "Age"])

# Use thresh=n to drop any data will less than n values in the dataframe
df_drop.dropna()

         0     1
0   Adrian  20.0
1  Bethany  23.0
2    Chloe  41.0

In [94]:

# Use axis=0 or 1, to drop the column on that axis
df_vert_drop = pd.DataFrame(data, columns=["Name", "Age"])

df_vert_drop.drop("Age", axis=1)

      Name
0   Adrian
1  Bethany
2    Chloe
3    David

In [129]:
data = [
    {"Name" : "Anthony", "Age" : 17, "Location" : "UK"},
    {"Name" : "Anthony", "Age" : 17, "Location" : "UK"},
    {"Name" : "Bobby",  "Age":  21, "Location" :  "UK"},
    {"Name" : "Caitlin", "Location" : "France"}
]


df = pandas.DataFrame(data)

In [131]:
# Data cleaning functions

# Returns index list
# df.index

# Returns key information about the DataFrame
# df.info(verbose=True)

# Returns array of the data in the DataFrame
# df.values

# Returns the shape of the DataFrame to use to locate items
# df.shape

# To find specific rows
#  df.loc[0]

# Returns duplicated information
# df.drop_duplicates()


# Select specfic columns
# df.filter(items = ["Name", "Age"])

# Drop any rows with na values
# df.dropna()

# Fills any na values with what you input
# df.fillna("Age not given")

# Sort by an axis
# df.sort_values("Age", ascending = False)


# Send to a different format
# df.to_json(path)
# df.to_excel(path)
# df.to_html(path)

      Name   Age Location
2    Bobby  21.0       UK
0  Anthony  17.0       UK
1  Anthony  17.0       UK
3  Caitlin   NaN   France

In [173]:
import csv 

df_csv = pd.read_csv("Day1_Sales.csv")

In [174]:
# df_csv

In [175]:
df_csv.head()

,OrderID,Date,CustomerName,Region,Product,Quantity,Price,Discount,Total
0,ORD0001,2023-04-13,Bob,North America,Tablet,4,49.99,0.10,179.96
1,ORD0002,2023-04-17,NaN,Africa,Monitor,8,49.99,0.00,399.92
2,ORD0003,2023-04-13,Alice,Africa,Smartphone,3,499.99,0.10,1349.97
3,ORD0004,2023-03-29,Hannah,africa,Tablet,5,999.99,0.15,4249.96
4,ORD0005,2023-01-24,Grace,Asia-Pacific,Tablet,3,49.99,0.05,142.47

In [176]:
df_csv.describe()

        Quantity       Price   Discount        Total
count  50.000000   50.000000  50.000000    50.000000
mean    5.280000  378.990000   0.090000  1893.651200
std     2.595443  332.597998   0.059761  2186.295381
min     1.000000   49.990000   0.000000    84.980000
25%     3.000000   87.490000   0.050000   362.427500
50%     5.000000  299.990000   0.100000  1232.450000
75%     8.000000  499.990000   0.150000  2812.470000
max     9.000000  999.990000   0.150000  8999.910000

In [177]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       50 non-null     object
 1   Date          50 non-null     object
 2   CustomerName  44 non-null     object
 3   Region        50 non-null     object
 4   Product       50 non-null     object
 5   Quantity      50 non-null     int64
 6   Price         50 non-null     float64
 7   Discount      50 non-null     float64
 8   Total         50 non-null     float64
dtypes: float64(3), int64(1), object(5)
memory usage: 3.6+ KB

In [178]:
df_csv.isnull().sum()

OrderID         0
Date            0
CustomerName    6
Region          0
Product         0
Quantity        0
Price           0
Discount        0
Total           0
dtype: int64

In [179]:
df_csv.duplicated().sum()

0

In [180]:
df_csv[df_csv["Price"] > 50].head()

,OrderID,Date,CustomerName,Region,Product,Quantity,Price,Discount,Total
2,ORD0003,2023-04-13,Alice,Africa,Smartphone,3,499.99,0.10,1349.97
3,ORD0004,2023-03-29,Hannah,africa,Tablet,5,999.99,0.15,4249.96
5,ORD0006,2023-03-29,Bob,South America,Laptop,6,299.99,0.15,1529.95
6,ORD0007,2023-03-01,Alice,South America,Headphones,5,199.99,0.15,849.96
8,ORD0009,2023-03-30,Diana,Asia-Pacific,Laptop,1,499.99,0.10,449.99

In [181]:
df_csv.drop(columns = ["Region", "Product"]).head()

   OrderID        Date CustomerName  Quantity   Price  Discount    Total
0  ORD0001  2023-04-13          Bob         4   49.99      0.10   179.96
1  ORD0002  2023-04-17          NaN         8   49.99      0.00   399.92
2  ORD0003  2023-04-13        Alice         3  499.99      0.10  1349.97
3  ORD0004  2023-03-29       Hannah         5  999.99      0.15  4249.96
4  ORD0005  2023-01-24        Grace         3   49.99      0.05   142.47

In [182]:
df_csv[["OrderID", "Product", "Quantity"]].head()

   OrderID     Product  Quantity
0  ORD0001      Tablet         4
1  ORD0002     Monitor         8
2  ORD0003  Smartphone         3
3  ORD0004      Tablet         5
4  ORD0005      Tablet         3

In [183]:
df_csv_1 = df_csv.copy()

df_csv_1["SubTotal"] = df_csv["Price"] * df_csv["Quantity"]
df_csv_1.head()

,OrderID,Date,CustomerName,Region,Product,Quantity,Price,Discount,Total,SubTotal
0,ORD0001,2023-04-13,Bob,North America,Tablet,4,49.99,0.10,179.96,199.96
1,ORD0002,2023-04-17,NaN,Africa,Monitor,8,49.99,0.00,399.92,399.92
2,ORD0003,2023-04-13,Alice,Africa,Smartphone,3,499.99,0.10,1349.97,1499.97
3,ORD0004,2023-03-29,Hannah,africa,Tablet,5,999.99,0.15,4249.96,4999.95
4,ORD0005,2023-01-24,Grace,Asia-Pacific,Tablet,3,49.99,0.05,142.47,149.97